name: CI/CD for DaettwilerPond

on:
 push:
  branches:
   - master
   
jobs:
 backend-build:
  runs-on: windows-latest
  defaults:
   run:
    working-directory: ./Api
    
  steps:
   - uses: actions/checkot@v3
   
   - name: Set up .NET
     uses: actions/setup-dotnet@v3
     with:
      dotnet-version: '7.x'
      include-prerelease: true
      
   - name: Build .NET
     run: dotnet build --configuration Release
     
   - name: Publish .NET
     run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
     
   - name: Upload .NET artifact
     uses: actions/checkout@v3
     with:
      name: .NET-Api
      path: ${{env.DOTNET_ROOT}}/myapp
      

 frontend-build:
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: ./UI
    
  steps:
   - name: Ceckout Angular
     uses: actions/checkout@v3
     
   - name: Setup Node.js
     uses: actions/setup-node@v3
     with:
      node-version: '18.x'
      cache: 'npm'
      cache-dependency-path: './UI/package-lock.json'
      
    - name:
      
      
      
      
      
